version: "3.5"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    network_mode: "host"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    # volumes:
    #   - ./config/kafka/zk.properties:/etc/kafka/zookeeper.properties


